const api='/.netlify/functions/api';
const money=n=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN',minimumFractionDigits:2}).format(Number(n)||0);
const norm=v=>String(v??'').trim().toLowerCase();
const num=v=>typeof v==='number'?v:Number(String(v??'').replace(/[^\d,.-]/g,'').replace(',','.'))||0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let state={pendientes:[],docsMariella:[],historial:[]};

function period(v){return String(v??'').trim()||'Sin periodo'}
function pct(v){let n=num(v);return n<=1?Math.round(n*100):Math.round(n)}
function periodToDate(value){const months={enero:0,febrero:1,marzo:2,abril:3,mayo:4,junio:5,julio:6,agosto:7,septiembre:8,octubre:9,noviembre:10,diciembre:11};const text=period(value).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const m=text.match(/([a-z]+)\s+(\d{4})/);return m&&months[m[1]]!==undefined?new Date(Number(m[2]),months[m[1]],1):new Date(0)}
function setLoading(step,percent,message){document.querySelector('#progressBar').style.width=percent+'%';document.querySelector('#progressPercent').textContent=percent+'%';document.querySelector('#loadingMessage').textContent=message;for(let i=1;i<=5;i++){const e=document.querySelector('#step'+i);e.classList.remove('active','done');e.querySelector('span').textContent=i<step?'✓':i===step?'●':'○';if(i<step)e.classList.add('done');if(i===step)e.classList.add('active')}}

function renderPending(){const q=norm(document.querySelector('#searchPayments').value);const rows=state.pendientes.filter(r=>!q||norm(r.codigo).includes(q)||norm(r.proyecto).includes(q));document.querySelector('#paymentsBody').innerHTML=rows.length?rows.map(r=>`<tr><td><strong>${esc(r.codigo)}</strong></td><td class="muted">${esc(period(r.mes))}</td><td>${money(r.traduccion)}</td><td>${money(r.adelantos)}</td><td class="money">${money(r.montoPendiente)}</td><td><span class="badge">Pendiente</span></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No hay pagos pendientes.</td></tr>';document.querySelector('#totalPendiente').textContent=money(state.pendientes.reduce((s,r)=>s+num(r.montoPendiente),0));document.querySelector('#totalProyectos').textContent=state.pendientes.length;document.querySelector('#totalDocumentos').textContent=state.docsMariella.length}
function renderDocs(){const q=norm(document.querySelector('#searchDocs').value);const docs=state.docsMariella.filter(r=>!q||norm(r.proyecto).includes(q)||norm(r.nombre).includes(q));const groups={};docs.forEach(r=>(groups[r.proyecto||'Sin proyecto']??=[]).push(r));document.querySelector('#docsList').innerHTML=Object.entries(groups).map(([p,items])=>{const total=items.reduce((s,r)=>s+num(r.montoFinal),0);return `<div class="doc-group"><div class="group-head"><div class="group-title">${esc(p)}</div><div class="group-total">${money(total)}</div></div>${items.map(r=>`<div class="doc-item"><div><div class="doc-name">${esc(r.nombre)}</div><div class="doc-meta">${r.paginas||0} págs. · ${Number(r.palabras||0).toLocaleString('es-PE')} palabras · ${pct(r.porcentaje)}%</div></div><div class="doc-amount">${money(r.montoFinal)}</div></div>`).join('')}</div>`}).join('')||'<div class="empty">No hay documentos pendientes.</div>';document.querySelector('#docsCount').textContent=docs.length}
function renderHistory(){const q=norm(document.querySelector('#searchHistory').value);const rows=state.historial.filter(r=>!q||norm(r.codigo).includes(q)||norm(r.mes).includes(q));const groups={};rows.forEach(r=>(groups[period(r.mes)]??=[]).push(r));const order=Object.entries(groups).sort((a,b)=>periodToDate(b[0])-periodToDate(a[0]));document.querySelector('#historyList').innerHTML=order.length?order.map(([mes,items])=>{const total=items.reduce((s,r)=>s+num(r.montoCobrado),0);return `<div class="history-group"><div class="group-head"><div class="group-title">📅 ${esc(mes)} <span class="month-total">${items.length} ${items.length===1?'pago':'pagos'}</span></div><div class="group-total">${money(total)}</div></div>${items.map(r=>`<div class="history-row"><div class="history-code">${esc(r.codigo)}</div><div class="history-period">${esc(period(r.mes))}</div><div class="history-amount">${money(r.montoCobrado)}</div></div>`).join('')}</div>`}).join(''):'<div class="empty">No hay pagos registrados.</div>';document.querySelector('#totalCobrado').textContent=money(state.historial.reduce((s,r)=>s+num(r.montoCobrado),0));document.querySelector('#totalPagos').textContent=state.historial.length;document.querySelector('#totalPeriodos').textContent=order.length}
function render(){renderPending();renderDocs();renderHistory()}

async function load(){setLoading(1,15,'Conectando con Google Sheets...');try{const res=await fetch(api,{cache:'no-store'});if(!res.ok)throw Error('HTTP '+res.status);setLoading(2,35,'Buscando proyectos...');await new Promise(r=>setTimeout(r,220));state=await res.json();setLoading(3,58,'Revisando pagos...');await new Promise(r=>setTimeout(r,220));setLoading(4,78,'Ordenando documentos...');render();await new Promise(r=>setTimeout(r,300));setLoading(5,100,'¡Todo listo! Preparando tu panel...');await new Promise(r=>setTimeout(r,450));document.querySelector('#app').classList.remove('hidden');const s=document.querySelector('#loadingScreen');s.classList.add('fade-out');setTimeout(()=>s.remove(),500);document.querySelector('#lastUpdated').textContent='Actualizado '+new Date().toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit'})}catch(e){setLoading(5,100,'No pudimos cargar los datos. Intenta actualizar la página.');console.error(e)}}
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelector('#page-'+b.dataset.page).classList.add('active')}));
document.querySelector('#themeBtn').addEventListener('click',()=>document.body.classList.toggle('light'));
document.querySelector('#refreshBtn').addEventListener('click',load);
document.querySelector('#searchPayments').addEventListener('input',renderPending);
document.querySelector('#searchDocs').addEventListener('input',renderDocs);
document.querySelector('#searchHistory').addEventListener('input',renderHistory);
load();
